import mongoose from "mongoose";

const expenseSchema = new mongoose.Schema({
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User"
  },
  category: String,
  spentAt: String,
  amount: Number,
  isRecurring: {
    type: Boolean,
    default: false
  },
  recurringFrequency: {
    type: String,
    default: null
  },
  recurringTemplateId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Expense",
    default: null
  },
  isAutoGenerated: {
    type: Boolean,
    default: false
  },
  recurringStartDate: {
    type: Date,
    default: null
  },
  recurringSkipMonths: {
    type: [String],
    default: []
  },
  recurrenceMonthKey: {
    type: String,
    default: ""
  },
  transactionDetails: String,
  account: String,
  otherTransactionDetails: String,
  upiRefNo: String,
  orderId: String,
  remarks: String,
  tag: String,
  source: String,
  sourceKey: String,
  date: {
    type: Date,
    default: Date.now
  }
});

export const Expense = mongoose.model('Expense' , expenseSchema)
