import { Expense } from "../models/Expanse.model.js";

const MONTHLY_FREQUENCY = "monthly";

const getMonthKey = (date) => {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, "0");
    return `${year}-${month}`;
};

const getMonthStart = (date) =>
    new Date(date.getFullYear(), date.getMonth(), 1, 0, 0, 0, 0);

const buildOccurrenceDate = (sourceDate, targetDate) => {
    const year = targetDate.getFullYear();
    const month = targetDate.getMonth();
    const day = sourceDate.getDate();
    const maxDay = new Date(year, month + 1, 0).getDate();
    const clampedDay = Math.min(day, maxDay);

    return new Date(
        year,
        month,
        clampedDay,
        sourceDate.getHours(),
        sourceDate.getMinutes(),
        sourceDate.getSeconds(),
        sourceDate.getMilliseconds()
    );
};

const monthIterator = function* (fromDate, toDate) {
    const cursor = new Date(fromDate.getFullYear(), fromDate.getMonth(), 1);
    const end = new Date(toDate.getFullYear(), toDate.getMonth(), 1);

    while (cursor <= end) {
        yield new Date(cursor);
        cursor.setMonth(cursor.getMonth() + 1);
    }
};

const syncRecurringExpenses = async (userId, asOf = new Date()) => {
    const templates = await Expense.find({
        userId,
        isRecurring: true,
        isAutoGenerated: { $ne: true },
        recurringFrequency: MONTHLY_FREQUENCY
    });

    if (!templates.length) {
        return { createdCount: 0 };
    }

    const templateIds = templates.map((item) => item._id);
    const linkedOccurrences = await Expense.find({
        userId,
        $or: [
            { _id: { $in: templateIds } },
            { recurringTemplateId: { $in: templateIds } }
        ]
    }).select("_id recurringTemplateId recurrenceMonthKey date");

    const monthsByTemplate = new Map();
    linkedOccurrences.forEach((item) => {
        const templateId = String(item.recurringTemplateId || item._id);
        const monthKey = item.recurrenceMonthKey || getMonthKey(new Date(item.date));
        if (!monthsByTemplate.has(templateId)) {
            monthsByTemplate.set(templateId, new Set());
        }
        monthsByTemplate.get(templateId).add(monthKey);
    });

    const docsToCreate = [];

    templates.forEach((template) => {
        const templateDate = new Date(template.recurringStartDate || template.date || new Date());
        const templateMonth = getMonthStart(templateDate);
        const endMonth = getMonthStart(asOf);
        const templateKey = String(template._id);
        const existingMonths = monthsByTemplate.get(templateKey) || new Set();
        const skippedMonths = new Set(template.recurringSkipMonths || []);

        for (const monthDate of monthIterator(templateMonth, endMonth)) {
            const monthKey = getMonthKey(monthDate);
            if (existingMonths.has(monthKey) || skippedMonths.has(monthKey)) {
                continue;
            }

            docsToCreate.push({
                userId: template.userId,
                category: template.category,
                spentAt: template.spentAt,
                amount: template.amount,
                isRecurring: true,
                recurringFrequency: MONTHLY_FREQUENCY,
                recurringTemplateId: template._id,
                isAutoGenerated: true,
                recurringStartDate: template.recurringStartDate || template.date,
                recurringSkipMonths: [],
                recurrenceMonthKey: monthKey,
                transactionDetails: template.transactionDetails,
                account: template.account,
                otherTransactionDetails: template.otherTransactionDetails,
                upiRefNo: template.upiRefNo,
                orderId: template.orderId,
                remarks: template.remarks,
                tag: template.tag,
                source: template.source || "recurring-expense",
                sourceKey: null,
                date: buildOccurrenceDate(templateDate, monthDate)
            });
            existingMonths.add(monthKey);
        }
    });

    if (!docsToCreate.length) {
        return { createdCount: 0 };
    }

    await Expense.insertMany(docsToCreate);
    return { createdCount: docsToCreate.length };
};

export { MONTHLY_FREQUENCY, getMonthKey, syncRecurringExpenses };
