import React, { useContext, useEffect, useMemo, useState } from 'react'
import axios from 'axios'
import { UserDataContext } from '../context/UserContext'
import { normalizeCategoryName } from '../constants/categories'
import CategorySelectField from '../componants/CategorySelectField'
import {
  buildReportFileName,
  downloadCsvReport,
  downloadPdfReport,
  formatReportCurrency,
  formatReportDate,
} from '../utils/reportExports'

const toFormDate = (value) => {
  if (!value) return ''
  const parsed = new Date(value)
  if (Number.isNaN(parsed.getTime())) return ''
  return parsed.toISOString().slice(0, 10)
}

const normalizeExpense = (item) => ({
  ...item,
  category: normalizeCategoryName(item.category),
})

const reportButtonClass =
  'rounded-full border border-slate-700/70 bg-slate-950/65 px-4 py-2 text-xs font-semibold text-slate-100 transition hover:-translate-y-0.5 disabled:cursor-not-allowed disabled:opacity-45'

const buildStatementRows = (report) => {
  if (!report) return []

  const paidRows = Array.isArray(report.expenses)
    ? report.expenses.map((item) => ({
        ...item,
        type: 'Paid',
        name: item.spentAt || item.transactionDetails || item.category,
      }))
    : []

  const receivedRows = Array.isArray(report.mainAccount?.entries)
    ? report.mainAccount.entries.map((item) => ({
        ...item,
        type: 'Received',
        category: 'Main Account',
        name: item.transactionDetails || item.account || 'Received credit',
      }))
    : []

  return [...paidRows, ...receivedRows].sort((a, b) => {
    const aValue = new Date(a.timestamp || a.date || 0).getTime()
    const bValue = new Date(b.timestamp || b.date || 0).getTime()
    return bValue - aValue
  })
}

const Expenses = () => {
  const { refreshUserProfile } = useContext(UserDataContext)
  const [expenses, setExpenses] = useState([])
  const [category, setCategory] = useState('')
  const [spentAt, setSpentAt] = useState('')
  const [amount, setAmount] = useState('')
  const [date, setDate] = useState('')
  const [isRecurring, setIsRecurring] = useState(false)
  const [selectedFile, setSelectedFile] = useState(null)
  const [loading, setLoading] = useState(false)
  const [uploading, setUploading] = useState(false)
  const [savingEdit, setSavingEdit] = useState(false)
  const [error, setError] = useState('')
  const [uploadError, setUploadError] = useState('')
  const [importResult, setImportResult] = useState(null)
  const [searchQuery, setSearchQuery] = useState('')
  const [filterCategory, setFilterCategory] = useState('')
  const [dateFrom, setDateFrom] = useState('')
  const [dateTo, setDateTo] = useState('')
  const [editingExpense, setEditingExpense] = useState(null)

  const token = localStorage.getItem('token') || ''
  const headers = token ? { Authorization: `Bearer ${token}` } : {}

  const fetchExpenses = async () => {
    setLoading(true)
    setError('')
    try {
      const res = await axios.get(
        `${import.meta.env.VITE_BASE_URL}/api/v1/expenses`,
        { headers }
      )
      const list = Array.isArray(res?.data?.data) ? res.data.data : []
      setExpenses(list.map(normalizeExpense))
    } catch (err) {
      setError(
        err?.response?.data?.message ||
          err?.message ||
          'Unable to load expenses.'
      )
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    fetchExpenses()
  }, [])

  const handleCreate = async (event) => {
    event.preventDefault()
    setError('')
    if (!category.trim() || !amount) {
      setError('Category and amount are required.')
      return
    }

    try {
      const res = await axios.post(
        `${import.meta.env.VITE_BASE_URL}/api/v1/expenses`,
        {
          category: category.trim(),
          spentAt: spentAt.trim() || undefined,
          amount: Number(amount),
          date: date || undefined,
          isRecurring,
        },
        { headers }
      )
      const created = res?.data?.data
      if (created) {
        setExpenses((prev) => [normalizeExpense(created), ...prev])
      }
      setCategory('')
      setSpentAt('')
      setAmount('')
      setDate('')
      setIsRecurring(false)
    } catch (err) {
      setError(
        err?.response?.data?.message ||
          err?.message ||
          'Unable to add expense.'
      )
    }
  }

  const beginEdit = (item) => {
    setEditingExpense({
      _id: item._id,
      category: normalizeCategoryName(item.category),
      spentAt: item.spentAt || '',
      amount: String(item.amount || ''),
      date: toFormDate(item.date),
      isRecurring: Boolean(item.isRecurring),
      isAutoGenerated: Boolean(item.isAutoGenerated),
    })
    setError('')
  }

  const handleEditChange = (field, value) => {
    setEditingExpense((prev) => (prev ? { ...prev, [field]: value } : prev))
  }

  const handleUpdateExpense = async (event) => {
    event.preventDefault()
    if (!editingExpense) return

    if (!editingExpense.category.trim() || !editingExpense.amount) {
      setError('Category and amount are required to update an expense.')
      return
    }

    setSavingEdit(true)
    setError('')

    try {
      const res = await axios.patch(
        `${import.meta.env.VITE_BASE_URL}/api/v1/expenses/${editingExpense._id}`,
        {
          category: editingExpense.category,
          spentAt: editingExpense.spentAt.trim() || null,
          amount: Number(editingExpense.amount),
          date: editingExpense.date || undefined,
          isRecurring: editingExpense.isRecurring,
        },
        { headers }
      )

      const updated = normalizeExpense(res?.data?.data)
      setExpenses((prev) =>
        prev.map((item) => (item._id === updated._id ? updated : item))
      )
      setEditingExpense(null)
      await refreshUserProfile?.()
    } catch (err) {
      setError(
        err?.response?.data?.message ||
          err?.message ||
          'Unable to update expense.'
      )
    } finally {
      setSavingEdit(false)
    }
  }

  const handleDelete = async (expenseId) => {
    try {
      await axios.delete(
        `${import.meta.env.VITE_BASE_URL}/api/v1/expenses/${expenseId}`,
        { headers }
      )
      setExpenses((prev) => prev.filter((item) => item._id !== expenseId))
      if (editingExpense?._id === expenseId) {
        setEditingExpense(null)
      }
      await refreshUserProfile?.()
    } catch (err) {
      setError(
        err?.response?.data?.message ||
          err?.message ||
          'Unable to delete expense.'
      )
    }
  }

  const handleUpload = async (event) => {
    event.preventDefault()
    setUploadError('')

    if (!selectedFile) {
      setUploadError('Choose a Paytm Excel statement first.')
      return
    }

    const formData = new FormData()
    formData.append('statement', selectedFile)

    setUploading(true)
    try {
      const res = await axios.post(
        `${import.meta.env.VITE_BASE_URL}/api/v1/expenses/import/paytm-passbook`,
        formData,
        {
          headers: {
            ...headers,
            'Content-Type': 'multipart/form-data',
          },
        }
      )

      setImportResult(res?.data?.data || null)
      setSelectedFile(null)
      await Promise.all([fetchExpenses(), refreshUserProfile?.()])
    } catch (err) {
      setUploadError(
        err?.response?.data?.message ||
          err?.message ||
          'Unable to import the statement.'
      )
    } finally {
      setUploading(false)
    }
  }

  const filteredExpenses = useMemo(() => {
    return expenses.filter((item) => {
      const query = searchQuery.trim().toLowerCase()
      const itemDate = toFormDate(item.date)
      const matchesQuery =
        !query ||
        [
          item.spentAt,
          item.transactionDetails,
          item.category,
          item.account,
          item.amount,
        ]
          .filter(Boolean)
          .some((value) => String(value).toLowerCase().includes(query))

      const matchesCategory =
        !filterCategory ||
        normalizeCategoryName(item.category) === normalizeCategoryName(filterCategory)

      const matchesFrom = !dateFrom || (itemDate && itemDate >= dateFrom)
      const matchesTo = !dateTo || (itemDate && itemDate <= dateTo)

      return matchesQuery && matchesCategory && matchesFrom && matchesTo
    })
  }, [dateFrom, dateTo, expenses, filterCategory, searchQuery])

  const totalSpend = expenses.reduce(
    (sum, item) => sum + Number(item.amount || 0),
    0
  )
  const filteredSpend = filteredExpenses.reduce(
    (sum, item) => sum + Number(item.amount || 0),
    0
  )
  const importedCredits = importResult?.mainAccount?.entries || []
  const statementRows = useMemo(
    () => buildStatementRows(importResult),
    [importResult]
  )
  const hasFilters = Boolean(searchQuery || filterCategory || dateFrom || dateTo)

  const exportExpenseColumns = [
    {
      label: 'Date',
      value: (item) => formatReportDate(item.date),
    },
    {
      label: 'Category',
      value: (item) => normalizeCategoryName(item.category),
    },
    {
      label: 'Spent At / Paid To',
      value: (item) =>
        item.spentAt || item.transactionDetails || 'Manual expense entry',
    },
    {
      label: 'Transaction Details',
      value: (item) => item.transactionDetails || '',
    },
    {
      label: 'Amount',
      value: (item) => Number(item.amount || 0).toFixed(2),
    },
    {
      label: 'Account',
      value: (item) => item.account || '',
    },
    {
      label: 'UPI Ref',
      value: (item) => item.upiRefNo || '',
    },
    {
      label: 'Recurring',
      value: (item) =>
        item.isRecurring ? (item.isAutoGenerated ? 'Auto-filled' : 'Yes') : 'No',
    },
    {
      label: 'Source',
      value: (item) => item.source || 'manual',
    },
  ]

  const exportStatementColumns = [
    {
      label: 'Type',
      value: (item) => item.type,
    },
    {
      label: 'Date',
      value: (item) => formatReportDate(item.timestamp || item.date),
    },
    {
      label: 'Category',
      value: (item) => item.category || '',
    },
    {
      label: 'Name / Details',
      value: (item) => item.name || '',
    },
    {
      label: 'Transaction Details',
      value: (item) => item.transactionDetails || '',
    },
    {
      label: 'Amount',
      value: (item) => Number(item.amount || 0).toFixed(2),
    },
    {
      label: 'Account',
      value: (item) => item.account || '',
    },
    {
      label: 'UPI Ref',
      value: (item) => item.upiRefNo || '',
    },
    {
      label: 'Remarks',
      value: (item) => item.remarks || '',
    },
  ]

  const handleExportExpensesCsv = () => {
    downloadCsvReport({
      fileName: buildReportFileName('expenses-report', 'csv'),
      metaRows: [
        ['Report', 'Expenses'],
        ['Entries', filteredExpenses.length],
        ['Filtered spend', Number(filteredSpend || 0).toFixed(2)],
        ['Search', searchQuery || 'All'],
        ['Category', filterCategory || 'All categories'],
        ['From date', dateFrom || 'Start'],
        ['To date', dateTo || 'End'],
      ],
      columns: exportExpenseColumns,
      rows: filteredExpenses,
    })
  }

  const handleExportExpensesPdf = () => {
    downloadPdfReport({
      fileName: buildReportFileName('expenses-report', 'pdf'),
      title: 'FinStreet Expenses Report',
      subtitleLines: ['Filtered expense history export'],
      summaryLines: [
        `Entries: ${filteredExpenses.length}`,
        `Filtered spend: ${formatReportCurrency(filteredSpend)}`,
        `Search query: ${searchQuery || 'All expenses'}`,
        `Category filter: ${filterCategory || 'All categories'}`,
        `Date range: ${dateFrom || 'Start'} to ${dateTo || 'End'}`,
      ],
      columns: exportExpenseColumns,
      rows: filteredExpenses,
      orientation: 'landscape',
    })
  }

  const handleExportStatementCsv = () => {
    downloadCsvReport({
      fileName: buildReportFileName(
        importResult?.source?.fileName || 'paytm-statement-report',
        'csv'
      ),
      metaRows: [
        ['Report', 'Imported statement'],
        ['Source file', importResult?.source?.fileName || 'statement.xlsx'],
        ['Transactions', importResult?.summary?.totalTransactions || 0],
        ['Paid entries', importResult?.summary?.expenseCount || 0],
        ['Received entries', importResult?.summary?.receivedCount || 0],
        ['Paid total', Number(importResult?.summary?.totalExpenses || 0).toFixed(2)],
        ['Received total', Number(importResult?.summary?.totalReceived || 0).toFixed(2)],
      ],
      columns: exportStatementColumns,
      rows: statementRows,
    })
  }

  const handleExportStatementPdf = () => {
    downloadPdfReport({
      fileName: buildReportFileName(
        importResult?.source?.fileName || 'paytm-statement-report',
        'pdf'
      ),
      title: 'FinStreet Imported Statement Report',
      subtitleLines: [
        `Source: ${importResult?.source?.fileName || 'statement.xlsx'}`,
      ],
      summaryLines: [
        `Total transactions: ${importResult?.summary?.totalTransactions || 0}`,
        `Paid entries: ${importResult?.summary?.expenseCount || 0} for ${formatReportCurrency(importResult?.summary?.totalExpenses || 0)}`,
        `Received entries: ${importResult?.summary?.receivedCount || 0} for ${formatReportCurrency(importResult?.summary?.totalReceived || 0)}`,
        `New expense records added: ${importResult?.importResult?.importedExpenseCount || 0}`,
        `New main account credits added: ${importResult?.importResult?.importedMainAccountCount || 0}`,
      ],
      columns: exportStatementColumns,
      rows: statementRows,
      orientation: 'landscape',
    })
  }

  return (
    <main className="min-h-[calc(100vh-80px)] bg-slate-950 text-slate-100">
      <div className="mx-auto w-full max-w-6xl px-6 py-12">
        <header className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between">
          <div>
            <p className="text-xs font-semibold uppercase tracking-[0.3em] text-emerald-300">
              Expenses
            </p>
            <h1 className="mt-4 text-3xl font-semibold text-white md:text-4xl">
              Track every spend
            </h1>
            <p className="mt-2 text-sm text-slate-400">
              Total spent: ₹{totalSpend}
            </p>
          </div>
        </header>

        <div className="mt-8 grid gap-6">
          <section className="rounded-3xl border border-slate-800 bg-slate-900/70 p-6 shadow-[0_30px_90px_rgba(15,23,42,0.45)]">
            <div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between">
              <div>
                <h2 className="text-lg font-semibold text-white">
                  Import Paytm passbook
                </h2>
                <p className="mt-2 max-w-2xl text-sm text-slate-400">
                  Upload the Excel statement and we will add paid entries to
                  expenses and received entries to your main account balance.
                </p>
              </div>
              <div className="flex flex-wrap items-center gap-2">
                <span className="rounded-full border border-sky-400/30 bg-sky-400/10 px-3 py-1 text-xs font-semibold text-sky-200">
                  SheetJS import
                </span>
                <button
                  type="button"
                  onClick={handleExportStatementCsv}
                  disabled={!statementRows.length}
                  className={reportButtonClass}
                >
                  Statement CSV
                </button>
                <button
                  type="button"
                  onClick={handleExportStatementPdf}
                  disabled={!statementRows.length}
                  className={reportButtonClass}
                >
                  Statement PDF
                </button>
              </div>
            </div>

            <form
              className="mt-6 grid gap-4 lg:grid-cols-[1fr_auto]"
              onSubmit={handleUpload}
            >
              <label className="flex flex-col gap-2 text-xs font-medium uppercase tracking-wide text-slate-400">
                Excel file
                <input
                  type="file"
                  accept=".xlsx,.xls"
                  onChange={(e) => setSelectedFile(e.target.files?.[0] || null)}
                  className="rounded-xl border border-slate-700/70 bg-slate-950/60 px-4 py-3 text-sm text-white outline-none file:mr-4 file:rounded-full file:border-0 file:bg-slate-800 file:px-4 file:py-2 file:text-xs file:font-semibold file:text-slate-100"
                />
              </label>
              <button
                type="submit"
                disabled={uploading}
                className="rounded-full bg-gradient-to-r from-amber-300 via-orange-300 to-rose-300 px-5 py-3 text-sm font-semibold text-slate-950 transition hover:-translate-y-0.5 disabled:cursor-not-allowed disabled:opacity-60"
              >
                {uploading ? 'Importing...' : 'Upload statement'}
              </button>
            </form>

            {uploadError ? (
              <div className="mt-4 rounded-2xl border border-rose-500/30 bg-rose-500/10 px-4 py-3 text-xs text-rose-200">
                {uploadError}
              </div>
            ) : null}

            {importResult ? (
              <div className="mt-6 grid gap-4 lg:grid-cols-[1.1fr_1fr]">
                <div className="rounded-2xl border border-slate-800 bg-slate-950/50 p-4">
                  <p className="text-xs uppercase tracking-[0.2em] text-slate-400">
                    Import summary
                  </p>
                  <div className="mt-4 grid gap-3 sm:grid-cols-2">
                    <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4">
                      <p className="text-xs text-slate-400">Transactions</p>
                      <p className="mt-2 text-2xl font-semibold text-white">
                        {importResult.summary?.totalTransactions || 0}
                      </p>
                    </div>
                    <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4">
                      <p className="text-xs text-slate-400">New expenses</p>
                      <p className="mt-2 text-2xl font-semibold text-white">
                        {importResult.importResult?.importedExpenseCount || 0}
                      </p>
                    </div>
                    <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4">
                      <p className="text-xs text-slate-400">Paid total</p>
                      <p className="mt-2 text-2xl font-semibold text-rose-200">
                        ₹{importResult.summary?.totalExpenses || 0}
                      </p>
                    </div>
                    <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4">
                      <p className="text-xs text-slate-400">Main account credits</p>
                      <p className="mt-2 text-2xl font-semibold text-emerald-200">
                        ₹{importResult.summary?.totalReceived || 0}
                      </p>
                    </div>
                  </div>
                </div>

                <div className="rounded-2xl border border-slate-800 bg-slate-950/50 p-4">
                  <div className="flex items-center justify-between">
                    <p className="text-xs uppercase tracking-[0.2em] text-slate-400">
                      Received preview
                    </p>
                    <span className="text-xs text-slate-500">
                      {importResult.importResult?.importedMainAccountCount || 0} new
                    </span>
                  </div>
                  <div className="mt-4 space-y-3">
                    {importedCredits.length ? (
                      importedCredits.slice(0, 4).map((item) => (
                        <div
                          key={item.sourceKey}
                          className="rounded-2xl border border-slate-800 bg-slate-900/60 px-4 py-3"
                        >
                          <p className="text-sm font-semibold text-white">
                            {item.transactionDetails}
                          </p>
                          <div className="mt-1 flex items-center justify-between gap-4 text-xs text-slate-400">
                            <span>{item.date}</span>
                            <span className="font-semibold text-emerald-200">
                              +₹{item.amount}
                            </span>
                          </div>
                        </div>
                      ))
                    ) : (
                      <div className="rounded-2xl border border-slate-800 bg-slate-900/60 px-4 py-6 text-center text-sm text-slate-400">
                        No received entries found in the uploaded sheet.
                      </div>
                    )}
                  </div>
                </div>
              </div>
            ) : null}
          </section>

          <div className="grid gap-6 lg:grid-cols-[1.05fr_1.35fr]">
            <section className="space-y-6">
              <div className="rounded-3xl border border-slate-800 bg-slate-900/70 p-6 shadow-[0_30px_90px_rgba(15,23,42,0.45)]">
                <h2 className="text-lg font-semibold text-white">New expense</h2>
                <form className="mt-6 space-y-4" onSubmit={handleCreate}>
                  <CategorySelectField
                    value={category}
                    onChange={setCategory}
                    helperText="Use the shared categories so your budget bars and expense charts stay aligned."
                  />
                  <label className="flex flex-col gap-2 text-xs font-medium uppercase tracking-wide text-slate-400">
                    Spent At / Paid To
                    <input
                      value={spentAt}
                      onChange={(e) => setSpentAt(e.target.value)}
                      className="rounded-xl border border-slate-700/70 bg-slate-950/60 px-4 py-3 text-sm text-white outline-none"
                      placeholder="Swiggy, IRCTC, Anjani Bairwa"
                    />
                    <span className="text-[11px] normal-case tracking-normal text-slate-500">
                      Add the shop, app, person, or merchant name for this expense.
                    </span>
                  </label>
                  <label className="flex flex-col gap-2 text-xs font-medium uppercase tracking-wide text-slate-400">
                    Amount
                    <input
                      type="number"
                      value={amount}
                      onChange={(e) => setAmount(e.target.value)}
                      className="rounded-xl border border-slate-700/70 bg-slate-950/60 px-4 py-3 text-sm text-white outline-none"
                      placeholder="1200"
                    />
                  </label>
                <label className="flex flex-col gap-2 text-xs font-medium uppercase tracking-wide text-slate-400">
                  Date
                  <input
                      type="date"
                      value={date}
                      onChange={(e) => setDate(e.target.value)}
                    className="rounded-xl border border-slate-700/70 bg-slate-950/60 px-4 py-3 text-sm text-white outline-none"
                  />
                </label>
                <label className="flex items-start gap-3 rounded-2xl border border-slate-800 bg-slate-950/45 px-4 py-3">
                  <input
                    type="checkbox"
                    checked={isRecurring}
                    onChange={(e) => setIsRecurring(e.target.checked)}
                    className="mt-0.5 h-4 w-4 rounded border-slate-600 bg-slate-900 text-emerald-400"
                  />
                  <span className="flex flex-col">
                    <span className="text-xs font-medium uppercase tracking-wide text-slate-300">
                      Monthly recurring expense
                    </span>
                    <span className="mt-1 text-[11px] normal-case tracking-normal text-slate-500">
                      Use this for rent, recharge, SIP, subscriptions, or utilities.
                      Future months will auto-fill from the selected date.
                    </span>
                  </span>
                </label>
                {error ? (
                  <div className="rounded-2xl border border-rose-500/30 bg-rose-500/10 px-4 py-3 text-xs text-rose-200">
                    {error}
                  </div>
                  ) : null}
                  <button
                    type="submit"
                    className="w-full rounded-full bg-gradient-to-r from-emerald-300 via-emerald-400 to-sky-400 px-4 py-3 text-sm font-semibold text-slate-950 transition hover:-translate-y-0.5"
                  >
                    Add expense
                  </button>
                </form>
              </div>

              {editingExpense ? (
                <div className="rounded-3xl border border-sky-400/25 bg-slate-900/75 p-6 shadow-[0_30px_90px_rgba(15,23,42,0.45)]">
                  <div className="flex items-center justify-between gap-4">
                    <div>
                      <p className="text-xs font-semibold uppercase tracking-[0.3em] text-sky-300">
                        Edit Expense
                      </p>
                      <h2 className="mt-3 text-lg font-semibold text-white">
                        Update this entry
                      </h2>
                    </div>
                    <button
                      type="button"
                      onClick={() => setEditingExpense(null)}
                      className="rounded-full border border-slate-700/70 bg-slate-950/60 px-4 py-2 text-xs font-semibold text-slate-200"
                    >
                      Cancel
                    </button>
                  </div>

                  <form className="mt-6 space-y-4" onSubmit={handleUpdateExpense}>
                    <CategorySelectField
                      value={editingExpense.category}
                      onChange={(value) => handleEditChange('category', value)}
                      helperText="Editing keeps the same shared category system used across budgets."
                    />
                    <label className="flex flex-col gap-2 text-xs font-medium uppercase tracking-wide text-slate-400">
                      Spent At / Paid To
                      <input
                        value={editingExpense.spentAt}
                        onChange={(e) =>
                          handleEditChange('spentAt', e.target.value)
                        }
                        className="rounded-xl border border-slate-700/70 bg-slate-950/60 px-4 py-3 text-sm text-white outline-none"
                        placeholder="Swiggy, IRCTC, Anjani Bairwa"
                      />
                    </label>
                    <div className="grid gap-4 sm:grid-cols-2">
                      <label className="flex flex-col gap-2 text-xs font-medium uppercase tracking-wide text-slate-400">
                        Amount
                        <input
                          type="number"
                          value={editingExpense.amount}
                          onChange={(e) =>
                            handleEditChange('amount', e.target.value)
                          }
                          className="rounded-xl border border-slate-700/70 bg-slate-950/60 px-4 py-3 text-sm text-white outline-none"
                        />
                      </label>
                      <label className="flex flex-col gap-2 text-xs font-medium uppercase tracking-wide text-slate-400">
                        Date
                        <input
                          type="date"
                          value={editingExpense.date}
                          onChange={(e) =>
                            handleEditChange('date', e.target.value)
                          }
                          className="rounded-xl border border-slate-700/70 bg-slate-950/60 px-4 py-3 text-sm text-white outline-none"
                        />
                      </label>
                    </div>
                    {!editingExpense.isAutoGenerated ? (
                      <label className="flex items-start gap-3 rounded-2xl border border-slate-800 bg-slate-950/45 px-4 py-3">
                        <input
                          type="checkbox"
                          checked={editingExpense.isRecurring}
                          onChange={(e) =>
                            handleEditChange('isRecurring', e.target.checked)
                          }
                          className="mt-0.5 h-4 w-4 rounded border-slate-600 bg-slate-900 text-sky-400"
                        />
                        <span className="flex flex-col">
                          <span className="text-xs font-medium uppercase tracking-wide text-slate-300">
                            Monthly recurring expense
                          </span>
                          <span className="mt-1 text-[11px] normal-case tracking-normal text-slate-500">
                            Keep this template active to auto-fill new months.
                          </span>
                        </span>
                      </label>
                    ) : (
                      <div className="rounded-2xl border border-sky-400/20 bg-sky-400/10 px-4 py-3 text-xs text-sky-100">
                        This entry was auto-filled from a recurring expense template.
                      </div>
                    )}
                    <button
                      type="submit"
                      disabled={savingEdit}
                      className="w-full rounded-full bg-gradient-to-r from-sky-300 via-cyan-300 to-emerald-300 px-4 py-3 text-sm font-semibold text-slate-950 transition hover:-translate-y-0.5 disabled:cursor-not-allowed disabled:opacity-60"
                    >
                      {savingEdit ? 'Saving changes...' : 'Save changes'}
                    </button>
                  </form>
                </div>
              ) : null}
            </section>

            <section className="rounded-3xl border border-slate-800 bg-slate-900/70 p-6 shadow-[0_30px_90px_rgba(15,23,42,0.45)]">
              <div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between">
                <div>
                  <h2 className="text-lg font-semibold text-white">
                    Manage expenses
                  </h2>
                  <p className="mt-1 text-sm text-slate-400">
                    Search, filter, and edit your recent spending history.
                  </p>
                </div>
                <div className="flex flex-wrap items-center justify-end gap-3">
                  <div className="rounded-2xl border border-slate-800 bg-slate-950/50 px-4 py-3 text-right">
                    <p className="text-xs uppercase tracking-[0.18em] text-slate-500">
                      Showing
                    </p>
                    <p className="mt-1 text-lg font-semibold text-white">
                      {filteredExpenses.length} / {expenses.length}
                    </p>
                    <p className="text-xs text-slate-400">₹{filteredSpend} filtered</p>
                  </div>
                  <button
                    type="button"
                    onClick={handleExportExpensesCsv}
                    disabled={!filteredExpenses.length}
                    className={reportButtonClass}
                  >
                    Expenses CSV
                  </button>
                  <button
                    type="button"
                    onClick={handleExportExpensesPdf}
                    disabled={!filteredExpenses.length}
                    className={reportButtonClass}
                  >
                    Expenses PDF
                  </button>
                </div>
              </div>

              <div className="mt-6 grid gap-4 rounded-3xl border border-slate-800 bg-slate-950/45 p-4">
                <label className="flex flex-col gap-2 text-xs font-medium uppercase tracking-wide text-slate-400">
                  Search
                  <input
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    className="rounded-xl border border-slate-700/70 bg-slate-950/70 px-4 py-3 text-sm text-white outline-none"
                    placeholder="Search by place, category, details, or amount"
                  />
                </label>

                <div className="grid gap-4 lg:grid-cols-[1fr_1fr_1fr_auto]">
                  <CategorySelectField
                    value={filterCategory}
                    onChange={setFilterCategory}
                    label="Filter Category"
                    placeholder="All categories"
                    emptyLabel="All categories"
                    helperText="Narrow the list to one category when reviewing budget-heavy spending."
                  />
                  <label className="flex flex-col gap-2 text-xs font-medium uppercase tracking-wide text-slate-400">
                    From date
                    <input
                      type="date"
                      value={dateFrom}
                      onChange={(e) => setDateFrom(e.target.value)}
                      className="rounded-xl border border-slate-700/70 bg-slate-950/70 px-4 py-3 text-sm text-white outline-none"
                    />
                  </label>
                  <label className="flex flex-col gap-2 text-xs font-medium uppercase tracking-wide text-slate-400">
                    To date
                    <input
                      type="date"
                      value={dateTo}
                      onChange={(e) => setDateTo(e.target.value)}
                      className="rounded-xl border border-slate-700/70 bg-slate-950/70 px-4 py-3 text-sm text-white outline-none"
                    />
                  </label>
                  <button
                    type="button"
                    onClick={() => {
                      setSearchQuery('')
                      setFilterCategory('')
                      setDateFrom('')
                      setDateTo('')
                    }}
                    className="rounded-full border border-slate-700/60 bg-slate-900/70 px-4 py-3 text-sm font-semibold text-slate-100 transition hover:-translate-y-0.5"
                  >
                    Clear
                  </button>
                </div>
              </div>

              <div className="mt-5 space-y-3">
                {filteredExpenses.length ? (
                  filteredExpenses.map((item) => (
                    <div
                      key={item._id}
                      className="grid gap-4 rounded-2xl border border-slate-800 bg-slate-950/50 px-4 py-4 md:grid-cols-[1fr_auto]"
                    >
                      <div className="min-w-0">
                        <div className="flex flex-wrap items-center gap-2">
                          <p className="text-sm font-semibold text-white">
                            {item.spentAt ||
                              item.transactionDetails ||
                              item.category}
                          </p>
                          <span className="rounded-full border border-slate-700/70 bg-slate-900/70 px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.18em] text-emerald-200">
                            {item.category}
                          </span>
                          {item.isRecurring ? (
                            <span
                              className={`rounded-full border px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.18em] ${
                                item.isAutoGenerated
                                  ? 'border-sky-400/25 bg-sky-400/10 text-sky-100'
                                  : 'border-amber-400/25 bg-amber-400/10 text-amber-100'
                              }`}
                            >
                              {item.isAutoGenerated ? 'Auto-filled' : 'Recurring'}
                            </span>
                          ) : null}
                        </div>
                        <p className="mt-1 text-xs text-slate-400">
                          {item.transactionDetails &&
                          item.transactionDetails !== item.spentAt
                            ? item.transactionDetails
                            : 'Manual expense entry'}
                        </p>
                        <div className="mt-3 flex flex-wrap gap-3 text-xs text-slate-500">
                          <span>
                            {item.date
                              ? new Date(item.date).toLocaleDateString()
                              : 'No date'}
                          </span>
                          {item.account ? <span>{item.account}</span> : null}
                          {item.upiRefNo ? <span>UPI Ref: {item.upiRefNo}</span> : null}
                        </div>
                      </div>

                      <div className="flex flex-col items-end justify-between gap-3">
                        <span className="text-base font-semibold text-sky-200">
                          -₹{item.amount}
                        </span>
                        <div className="flex items-center gap-2">
                          <button
                            type="button"
                            onClick={() => beginEdit(item)}
                            className="rounded-full border border-sky-400/30 bg-sky-400/10 px-3 py-1.5 text-xs font-semibold text-sky-100 transition hover:-translate-y-0.5"
                          >
                            Edit
                          </button>
                          <button
                            type="button"
                            onClick={() => handleDelete(item._id)}
                            className="rounded-full border border-rose-400/30 bg-rose-400/10 px-3 py-1.5 text-xs font-semibold text-rose-100 transition hover:-translate-y-0.5"
                          >
                            Delete
                          </button>
                        </div>
                      </div>
                    </div>
                  ))
                ) : (
                  <div className="rounded-2xl border border-slate-800 bg-slate-950/50 px-4 py-6 text-center text-sm text-slate-400">
                    {loading
                      ? 'Fetching expenses...'
                      : hasFilters
                        ? 'No expenses matched your filters.'
                        : 'No expenses yet.'}
                  </div>
                )}
              </div>
            </section>
          </div>
        </div>
      </div>
    </main>
  )
}

export default Expenses
